site_name: Sablekh API Docs
theme: readthedocs
nav:
    - Home: index.md
    - Headers: headers.md
    - Authentication & Authorization: auth.md
    - User: user.md
    - Library: library.md
    - File: file.md
    - Download: download.md
    - Search: search.md
    - Tag: tag.md 
    - Verification & Reset: verify.md
    - Likes & Downloads: likes.md
