# Generated by Django 3.0.8 on 2020-08-03 19:55

from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_auto_20200730_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('hid', models.CharField(max_length=56, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1500)),
                ('link_str', models.CharField(max_length=350, unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('no_files', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('hid', models.CharField(max_length=56, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Library')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Visitor')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Visitor'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('hid', models.CharField(max_length=56, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('_file', models.FileField(upload_to='files')),
                ('size', models.IntegerField(default=0)),
                ('library', models.ForeignKey(blank='true', null='true', on_delete=django.db.models.deletion.CASCADE, to='api.Library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Visitor')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLot',
            fields=[
                ('zip_name', models.CharField(max_length=56, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), size=None)),
                ('downloads', models.IntegerField(default=0)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Library')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Visitor')),
            ],
        ),
    ]
