# Generated by Django 3.0.8 on 2020-07-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='link_str',
            field=models.CharField(max_length=350, unique=True),
            preserve_default=False,
        ),
    ]
